workflow:
  auto_cancel:
    on_new_commit: conservative
    on_job_failure: all

default:
  tags:
    - docker-52-1-21
    - rust

#setup:
#  stage: .pre
#  script:
#    - sudo apt-get update -y
#    - sudo apt-get install -y unzip
#    - curl -OL https://github.com/google/protobuf/releases/download/v3.20.3/protoc-3.20.3-linux-x86_64.zip
#    - unzip protoc-3.20.3-linux-x86_64.zip -d protoc3
#    - sudo mv protoc3/bin/* /usr/local/bin/
#    - sudo rm -rf /usr/local/include/google
#    - sudo mv protoc3/include/* /usr/local/include/

clean-docker:
  stage: .pre
  script:
    - docker system prune -a -f --volumes
    - docker compose rm -f -s -v

update-rust:
  stage: .pre
  script:
    - rustup update

fmt:
  script:
    - cargo fmt --all -- --check

build:
  script:
    - cargo build --verbose

clippy:
  script:
    - cargo clippy -- -D warnings

test:
  script:
    - SSL_CERT_FILE="./tls/ca.pem" cargo test -- --nocapture
  timeout: 10 minutes

push-image:
  stage: deploy
  script:
    - echo VERSION_TAG=$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID > .env
    - echo >> .env
    - echo IP_INFO_API_KEY=$IP_INFO_API_KEY >> .env
    - docker compose build
    - docker compose push
